datasource:
  driverName: mysql
  dataSourceName: sandaiyidui:qingxun@tcp(124.223.112.154:3306)/douyin
redis:
  host: 124.223.112.154
  port: 6379
  password: 

server:
  port: 8801

# 视频的存放地址
video:
  videoUrl: http://124.223.112.154:9091/douyin/feed/video/  # 这个是获取视频流服务器的接口地址
  imageUrl: https://cdn.pixabay.com/photo/2016/03/27/18/10/ #服务器上传文件并没有这封面好像
  filePath: videos/ # 如果存放本机的话 这个就是服务器中视频存放的目录
